version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.56.1
    - 4.56.2
    - 4.57.0
    - 4.58.0
    - 4.59.0
    - 4.60.0
  - dependency-name: docutils
    versions:
    - "0.17"
  - dependency-name: marshmallow
    versions:
    - 3.10.0
    - 3.11.0
    - 3.11.1
  - dependency-name: cryptography
    versions:
    - "3.2"
    - 3.4.7
  - dependency-name: keyring
    versions:
    - 23.0.1
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: twine
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.1
  - dependency-name: python-magic
    versions:
    - 0.4.18
    - 0.4.22
  - dependency-name: more-itertools
    versions:
    - 8.6.0
    - 8.7.0
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: certifi
    versions:
    - 2020.12.5
  - dependency-name: dataclasses-json
    versions:
    - 0.5.2
  - dependency-name: six
    versions:
    - 1.15.0
